name = "cybearbots-cbmail"
main = "worker/index.js"
compatibility_date = "2026-07-01"

routes = [
  { pattern = "cbmail.cybearbots.org", custom_domain = true }
]

[triggers]
crons = ["0 3 * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "cbmail-db"
database_id = "35af1dcf-cd61-4a24-9862-cb18865395d4"
